## Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
#spring:
#  application:
#    name: yyn-mq
#  # 数据库设置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/yyn_dev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 123456
#  # Nacos认证信息
#  cloud:
#    nacos:
#      discovery:
#        username: nacos
#        password: nacos
#        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
#        server-addr: 192.168.195.128:8848
#        # 注册到 nacos 的指定 namespace，默认为 public
#        namespace: public
#    sentinel:
#      transport:
#        port: 8722
#        dashboard: localhost:8090
#    stream:
#      bindings:
#        one-to-one-input:
#          destination: one-to-one  # 主题
#          contentType: application/json
#          group: one-to-one-cus-group # 消费者分组
#          consumer:
#            max-attempts: 1   # 最大重试次数
#        one-to-one-output:
#          destination: one-to-one  # 主题
#          contentType: application/json
#        one-to-many-input:
#          destination: one-to-many  # 主题
#          contentType: application/json
#          group: one-to-many-cus-group # 消费者分组
#        one-to-many-output:
#          destination: one-to-many  # 主题
#          contentType: application/json
#
#      rocketmq:
#        binder:
#          name-server: 192.168.195.128:9876  # RocketMQ NameServer 地址
#        bindings:
#          one-to-one-input:
#            consumer:
#              enabled: true # 是否开启消费，默认为 true
#              broadcasting: false # 是否使用广播消费，默认为 false 使用集群消费
#          one-to-one-output:
#            producer:
#              group: test # 生产者分组
#              sync: true # 是否同步发送消息，默认为 false 异步。
#              delay-level-when-next-consume: -1 # 异步消费消息模式下消费失败重试策略，默认为 brocker 0  1-consumer控制 -1 直接进入死信
#          one-to-many-input:
#            consumer:
#              enabled: true # 是否开启消费，默认为 true
#              messageModel: BROADCASTING  # 将消费模式改为广播模式
#
#
#
#
#server :
#  port : 8085
#  servlet:
#    context-path: /yynmq
#
## sentinel
#feign:
#  sentinel:
#    enabled: true
#
#
#
## mybatis-plu设置
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*.xml #扫描的xml文件路径
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台日志输出
